notes/urls.py
from django.urls import path, include
from notes import views


urlpatterns = [    
    path('', views.index, name = 'Home'),
    path('edit_note/',views.edit_note,name='EditNote'),
    path('Deletenote/', views.delete_note, name='DeleteNote'),
    path('signup/',views.signup, name='Signup'),
    path('login/',views.Userlogin, name='Login'),
    path('logout/',views.UserLogout, name='Logout'),
    
]

social_sec/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),    
    path('', include('notes.urls')),
    
]

notes/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Note(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=200, null = True)
    user = models.ForeignKey(User, on_delete= models.CASCADE )

    def  __str__(self):
        return self.title

notes/views.py
from django.shortcuts import render, redirect
from django.http  import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth  import authenticate, login,logout
#from django.contrib.auth import get_user_model
from notes.form import UserRegistrationForm, UserLoginForm,NoteForm
from django.contrib import messages
from django.http import JsonResponse 
from notes.models import Note

def index(request):
    if request.user.is_authenticated:
        form  = NoteForm()
        notes = Note.objects.filter(user = request.user ).order_by('-id') 
        
        data = {
            'form':form,
            'notes':notes
        }
        if request.method=="POST":
            title = request.POST.get('title')
            description = request.POST.get('description')
            print(title,description)
            note = Note()
            note.title = title
            note.description = description
            note.user = request.user
            note.save()
            notes = Note.objects.values().filter(user = request.user).order_by('-id')
            user_notes = list(notes)
            return JsonResponse({"status":"1" , "status_message":"Your Note Added Successfully","notes":user_notes})
        return render(request,template_name='notes/index.html',context = data)
    else:
        return redirect('Login')
        
def edit_note(request):
    edit_id = request.POST.get('edit_id')
    title = request.POST.get('title')
    description = request.POST.get('description')   
    Note.objects.filter(id = edit_id).update(title = title, description = description)
    notes = Note.objects.values().filter(user = request.user).order_by('-id')
    user_notes = list(notes)
    return JsonResponse({"status":"1" ,"status_message":"Your Note Upadated Successfully","notes":user_notes})


def delete_note(request):
    delete_id = request.GET.get('delete_id')
    print(delete_id)                                
    Note.objects.filter(id=delete_id).first().delete()
    notes = Note.objects.values().filter(user = request.user).order_by('-id')
    user_notes = list(notes)
    return JsonResponse({"status":"1" ,"status_message":"Your Note Deleted Successfully","notes":user_notes})

def signup(request):
    form = UserRegistrationForm
    data = {
        'form':form,
    }
    if request.method == 'POST':
        #form = UserRegistrationForm(request.POST)
        #print(form)
        name = request.POST.get('name')
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        re_password = request.POST.get('re_password')

        if (password != re_password):
            #messages.add_message(request, messages.INFO , 'Password do not match' )
            messages.error(request, 'Password do not match')
        else:
            user = User.objects.create_user(username = username,password = password,email = email, first_name = name)
            #user.save

            #UserModel = get_user_model()
            #user = UserModel.objects.create(username= username, password=password,email = email, first_name = name)
            #user.save()

            if (user.is_active):
                print('register')
                messages.success(request, 'User created')
                
            else:
                print('error')

    return render(request, template_name='notes/signup.html',  context=data)


def Userlogin(request):
    form = UserLoginForm
    data = {
        'form':form,
    }
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        try:
            user = authenticate(request,username = username , password = password)
        except:
            return JsonResponse({"status":"Invalid Credential"})
        
        if user is not None:
            login(request,user)
            return JsonResponse({"status":"User Login Success"})            
        else:
            return JsonResponse({"status":"Invalid Credential"})
        
        print(username, password)
    return render(request,template_name="notes/login.html", context= data)

def UserLogout(request):
    logout(request)
    return redirect('Login')

notes/templates/notes/index.html
{%  extends 'notes/layout.html' %}
{%  load crispy_forms_tags %}

{% block body %}
  {{request.user.username}} - {{request.user.email}}
  <p>You Can logout from here <a class="btn btn-success"  href=" {% url 'Logout' %}">Logout here</a> </p>
  <div class="container">
    <div class="row">
      
      <div class="col-lg-4 mt-3 mb-3">  
          
          <div class="col-11 mx-sm-auto rounded border p-3">  
            <h4 class="pt-3 pb-4">Add Yor Notes Here</h4>
            <p class="text-white text-center"  id="message"></p>
            <form id="noteForm" >
              {% csrf_token  %}
              {{form | crispy}}
              <input type="submit" class="btn btn-success btn-sm p-2 m-3" value="Add Note" id="add">
             
          </form>              
          </div>
      </div>    





      <div class="col-lg-8 mt-3 mb-3">
        
          <table class="table" id="notesTable">
              <thead>
                  <tr>
                      <th scope="col">S.No</th>
                      <th scope="col">Title</th>
                      <th scope="col">Description</th>
                      <th scope="col">Edit</th>
                      <th scope="col">Delete</th>
                  </tr>  
              </thead>  
              <tbody>
              
                {% for note in notes %}
                <tr>
                    <th scope="row">{{forloop.counter}}</th>
                    <td class="title">{{note.title}}</td>
                    <td class="description">{{note.description}}</td>
                    <td><button data="{{note.id}}" class="btn btn-primary edit">Edit</button></td>
                    <td><button data="{{note.id}}" class="btn btn-danger delete">Delete</button></td>
                </tr>
                {% endfor %}
              
              </tbody>  

          </table>
      </div>
    </div>
  </div>  
 

  <script src="https://code.jquery.com/jquery-3.7.1.js" 
  integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous">
 </script> 
 <script src="//cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
 
 
 <script>
  
        $(document).ready(function () {                
                $('#notesTable').DataTable();
        });
        let activeItem = null
    function showNote(data){
      $('#notesTable tbody').empty()
      for(i=0; i < data.length ; i++){
          $('#notesTable tbody').append(
            `
            <tr>
              <th scope="row">${i+1}</th>
              <td class="title">${data[i].title}</td>
              <td class="description">${data[i].description}</td>
              <td><button data="${data[i].id}" class="btn btn-primary edit">Edit</button></td>
              <td><button data="${data[i].id}" class="btn btn-danger delete">Delete</button></td>
            </tr>   
            
            `
          )
      }      
    }    
    function editItem(item){
        var title = item.find('.title').text()
        var description = item.find('.description').text()
        var edit_id = item.find('.edit').attr('data')
        console.log(title, description, edit_id)
        $('#id_title').val(title)
        $('#id_description').val(description)
        $('#add').val('Update Note')
        $('#add').removeClass('bg-success')
        $('#add').addClass('bg-danger')
        activeItem = edit_id
    }   
    
    function deleteNote(delete_id){
        $.ajax({
            type:'GET',
            url :'{% url 'DeleteNote' %}',
            data:{
                'delete_id' : delete_id,
            },
            success:function(response){
                console.log(response.notes)
                showNote(response.notes)
                $('.delete').click(function(){
                  var delete_id = $(this).attr('data')
                  console.log(delete_id)
                  deleteNote(delete_id)
                })
                $('.edit').click(function(){
                  var item = $(this).closest('tr')
                  editItem(item)
                })                                   
            }
        })
    }

    //This for from submission
    $(document).on('submit','#noteForm', function(e){
        e.preventDefault();
        title = $('#id_title').val();
        description = $('#id_description').val()
        url = '{% url "Home" %}'
        data = {
          'title':title,
          'description':description,
          csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
        }
        if (activeItem != null){
          url = '{% url "EditNote" %}'
          data['edit_id'] = activeItem
        }
        $.ajax({
            type:'POST',
            url:url,
            data:data,
            success:function(response){
              console.log(response)
              console.log(response.notes)
              data = response.notes
              
              if(response.status == "1"){
                $("#noteForm").trigger("reset");
                $("#id_title").focus();

                showNote(data)  


              }
              $('#message').text(response.status_message)
              $('#message').removeClass('bg-warning')
              $('#message').addClass('bg-success')
              $('#message').addClass('p-2')
              $('.edit').click(function(){
                var item = $(this).closest('tr')
                editItem(item)
              })                  

              $('.delete').click(function(){
                var delete_id = $(this).attr('data')
                console.log(delete_id)
                deleteNote(delete_id)
              })

              if(response.status_message == "Your Note Updatee Succesfully")
                  $('#message').text(response.status_message)
                  $('#message').removeClass('bg-success')
                  $('#message').addClass('bg-warning')
                  $('#add').val('Add Note')
                  $('#add').removeClass('bg-danger')
                  $('#add').addClass('bg-success')
                  activeItem = null

            }
        })
    })
   
    $('.edit').click(function(){
      var item = $(this).closest('tr')
      editItem(item)
    })    
    $('.delete').click(function(){
        var delete_id = $(this).attr('data')
        console.log(delete_id)
        deleteNote(delete_id)
    })
 </script> 
{% endblock %}

notes/templates/notes/layout.html
<!DOCTYPE html>
<html lang="en">
  {% load static  %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    
    
    

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">


    <link rel='stylesheet' href={% static 'notes/css/style.css' %} >
         
  </head>
  <body>
    <header>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
              <a class="navbar-brand" href="#">Navbar</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Dropdown
                    </a>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="#">Action</a></li>
                      <li><a class="dropdown-item" href="#">Another action</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link disabled" aria-disabled="true">Disabled</a>
                  </li>
                </ul>
                <form class="d-flex" role="search">
                  <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
              </div>
            </div>
          </nav>
    </header>   
    {% block body %}
    
    {% endblock %}
    
   
  
 

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
     
  </body>
</html>

notes/templates/notes/login.html
{%  extends 'notes/layout.html' %}
{%  load crispy_forms_tags %}
{% block body %}
    <div class="container col-4 border rounded p-3">
        <h3 class="mt-3 mb-4">Hello Login User </h4>
        <p id="message" class="text-white"></p>  
        <form method="POST" id="loginForm"> 
          {% csrf_token %}
          {{form|crispy}}
          <input type="submit" class="btn btn-success m-3" value="Login">
            
        </form>
    </div>
    <script src="https://code.jquery.com/jquery-3.7.1.js" 
    integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous">
    </script>  
    <script>
        $(document).on('submit','#loginForm',function(e){
            e.preventDefault();
            var username = $('#id_username').val()
            var password = $('#id_password').val()

            $.ajax({
                type: 'POST',
                url: '/login/',
                data:{
                    'username':username,
                    'password':password,
                    csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),

                },
                success:function(response){
                    console.log(response.status);
                    $('#message').text(response.status)
                    $('#message').addClass("p-2");
                    if(response.status == "User Login Success"){
                        $('#message').addClass('bg-success');
                        window.location = "{% url 'Home' %}";
                    }
                    else{
                      $('#message').addClass('bg-danger');
                    }

                }
            })
        })
    </script>     
{% endblock %}

notes/templates/notes/signup.html
{%  extends 'notes/layout.html' %}
{%  load crispy_forms_tags %}

{% block body %}

{% if messages %}
<ul class="messages">
    {% for message in messages %}           
    <li id = "error_text"  {% if message.tags %} class="bg-{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

  <div class="container border p-4 rounded col-4 ">
      <p id="error" class="text-white"></p>
      <h4 class="p-3">Signup Form</h4>
      <form method="POST" action="{% url 'Signup' %}" id="signupForm">
        {{form|crispy}}
        <input class="btn btn-sm btn-success m-3 p-1" type="submit" value="Signup">
        {% csrf_token  %}
      </form>
  </div>  
  
  <script src="https://code.jquery.com/jquery-3.7.1.js" 
          integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous">
  </script>   
  <script>
    $(document).on('submit','#signupForm', function(e){
        e.preventDefault();
        var name = $('#id_name').val()
        var username = $('#id_username').val()
        var email = $('#id_Email').val()
        var password = $('#id_password').val()
        var re_password = $('#id_re_password').val()
        // ajax call
        $.ajax({
          type: 'POST',
          url : '/signup/',
          data: {
            name :name,
            username :username,
            email :email,
            password :password,
            re_password :re_password,
            csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
          },
          success:function(response){
            console.log(response)
            var error = $(response).find('#error_text')
            console.log(error)
            var error_class = $(error).attr('class')
            console.log(error_class)  
            console.log(error.text())
            $('#error').addClass(error_class)
            $('#error').addClass('p-2')
            $('#error').text(error.text())
            if(error.text()=='User created'){
              window.location = "{%  url 'Login' %}"
            }
          }
        })
    })
  </script>
{% endblock %}